### ISSUE TITLE
Current distro fails on "perl in space" (in dir with space in name) due to old Dist-Zilla-Plugin-Test-Compile

### ISSUE THREAD

**Issue by mohawk2** [rkitover/string-toidentifier-en#2]
The current distro has `t/00-compile.t`:

```perl
    like( qx{ $^X -Ilib -e "require $_; print '$_ ok'" }, qr/^\s*$_ ok/s, "$_ loaded ok" )
```

which fails when `$^X` has spaces. Could you re-release with latest `Dist::Zilla::Plugin::Test::Compile` which fixes this?

**Comment by rkitover** [comment]
Uploaded 0.12, does this fix the problem?

**Comment by mohawk2** [comment]
It absolutely does! Thanks for such a quick turnaround.
